import Head from 'next/head'
import Image from 'next/image'

import { Inter } from '@next/font/google'
import axios from 'axios'
import { useEffect, useState, useRef, MutableRefObject } from 'react'
import Router, { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

  const {query, isReady} = useRouter()
  const [status, setStatus] = useState<boolean>(true)
  const roomName = useRef() as MutableRefObject<HTMLInputElement>
  const phoneNumber = useRef() as MutableRefObject<HTMLInputElement>
  const event = query.event

  useEffect (() => {
    if (!isReady) return;

    checkEvent()

    return () => {
      
    }
  })

  const checkEvent =  () => {

   axios.get('https://livedemo.ptintel.hk/api/event?id=' + event)
  .then((res) => {
    console.log(res.data);
    setStatus(status => res.data.event.isActive)
    
  })
  .catch((error) => {
    console.log(error);
    
  })
    
    

  }

  const onSubmit = () => {
    console.log(phoneNumber.current?.value)
    console.log(roomName.current?.value);
    Router.push({
      pathname: '/joiner',
      query: {
        room: roomName.current?.value,
        tel: phoneNumber.current?.value
      }
    })
  }

  

  return (
    <>
      <Head>
        <title>Bingo Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full min-h-screen flex flex-col justify-center items-center bg-gray-900'>
        <div className='relative w-[380px] h-[420px] bg-gray-800 rounded-lg overflow-hidden'>
          <div className=' absolute w-[380px] h-[420px] bg-gradient-to-r from-purple-500 via-purple-500 
          to-transparent -top-[50%] -left-[50%] animate-spin origin-bottom-right'>
          </div>

          <div className=' absolute w-[380px] h-[420px] bg-gradient-to-r from-blue-500 via-blue-500 
          to-transparent -top-[50%] -left-[50%] animate-spin origin-bottom-right'>
          </div>
          
          <div className='absolute inset-1 bg-gray-800 rounded-lg z-10 p-5'>

          {
            (status) ?
            <section className='flex justify-center flex-col items-center'>
              <h2 className='text-xl font-semibold text-purple-500 text-center mb-5'>Join Game</h2>

              <div className='w-full relative z-10 border-2 rounded-lg border-white h-10 bg-transparent text-gray-100 outline-none px-2 flex items-center mb-5'>
                <input type="text" ref={roomName} className='w-full bg-transparent outline-none placeholder-gray-700' placeholder='Enter Room Name'/>
              </div>

              <div className='w-full relative z-10 border-2 rounded-lg border-white h-10 bg-transparent text-gray-100 outline-none px-2 flex items-center mb-5'>
                <input type="tel" ref={phoneNumber} className='w-full bg-transparent outline-none placeholder-gray-700' placeholder='Enter Phone Number'/>
              </div>



              <button type="submit" className=' w-40 rounded-lg bg-purple-500 hover:bg-blue-500 text-gray-100 py-2 px-5' onClick={onSubmit}>Join Now</button>
            </section>
            :
            <section>
              <h2 className='text-xl font-semibold text-red-500 text-center mb-5'>Event is not available</h2>
            </section>
          }
            
          </div>
        </div>
      </div>
    </>
  )
}
